<?php
/**
 * TL_ROOT/system/modules/backend_user_online/languages/lv/default.php 
 * 
 * Contao extension: backend_user_online 1.0.1 stable 
 * Latvian translation file 
 * 
 * Copyright : &copy; 2007..2011 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Maris Celmins (warrior) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_member_onlineicon']['lastlogin'] = "Pēdējais Login";
$GLOBALS['TL_LANG']['MSC']['tl_member_onlineicon']['lastlogin_never'] = "nav autorizējies";
$GLOBALS['TL_LANG']['MSC']['tl_user_onlineicon']['lastlogin'] = "Pēdējais Login";
$GLOBALS['TL_LANG']['MSC']['tl_user_onlineicon']['lastlogin_never'] = "nav autorizējies";
 
?>
