<?php
/**
 * TL_ROOT/system/modules/backend_user_online/languages/fr/default.php 
 * 
 * Contao extension: backend_user_online 1.2.0 rc1 
 * Französisch translation file 
 * 
 * Copyright : &copy; 2007..2012 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_member_onlineicon']['lastlogin']['0'] = "Dernière connexion";
$GLOBALS['TL_LANG']['MSC']['tl_member_onlineicon']['lastlogin']['1'] = "Dernière connexion: %s";
$GLOBALS['TL_LANG']['MSC']['tl_member_onlineicon']['lastlogin_never'] = "Jamais connecté";
$GLOBALS['TL_LANG']['MSC']['tl_user_onlineicon']['lastlogin']['0'] = "Dernière connexion";
$GLOBALS['TL_LANG']['MSC']['tl_user_onlineicon']['lastlogin']['1'] = "Dernière connexion: %s";
$GLOBALS['TL_LANG']['MSC']['tl_user_onlineicon']['lastlogin_never'] = "Jamais connecté";
 
?>
