<?php
/**
 * TL_ROOT/system/modules/backend_user_online/languages/fr/default.php 
 * 
 * TYPOlight extension: backend_user_online 1.0.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007..2010 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.typolight.glen-langer.de 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tl_member_onlineicon']['lastlogin'] = "Dernière connexion";
$GLOBALS['TL_LANG']['MSC']['tl_member_onlineicon']['lastlogin_never'] = "Jamais connecté";
$GLOBALS['TL_LANG']['MSC']['tl_user_onlineicon']['lastlogin'] = "Dernière connexion";
$GLOBALS['TL_LANG']['MSC']['tl_user_onlineicon']['lastlogin_never'] = "Jamais connecté";
 
?>
